runtime: nodejs18

# Environment variables (set secrets via Secret Manager instead of hardcoding)
env_variables:
  NODE_ENV: "production"
  PORT: "8080"

# Automatic scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6

# Health check configuration
readiness_check:
  path: "/health"
  timeout_sec: 4
  check_interval_sec: 5
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  timeout_sec: 4
  check_interval_sec: 10
  failure_threshold: 4
  success_threshold: 2

# Resource allocation
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
